jobs:
  deploy:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup:
          app-name: serverless-framework-orb
          org-name: circleci
      - run:
          command: serverless install plugin --name serverless-pseudo-parameters
          name: install-plugins
      - run:
          command: serverless deploy -v
          name: deploy
orbs:
  aws-cli: circleci/aws-cli@1.2.1
  node: circleci/node@3.0.1
  serverless: circleci/serverless-framework@1.0.1
version: 2.1
workflows:
  deploy:
    jobs:
      - node/test:
          version: 13.11.0
      - deploy:
          requires:
            - node/test
          context: deckmasterweb-serverless