jobs:
  deploy:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup:
          app-name: serverless-framework-orb
          org-name: circleci
      - run:
          command: serverless deploy -v
          name: deploy
orbs:
  aws-cli: circleci/aws-cli@x.y
  node: circleci/node@x.y
  serverless: circleci/serverless-framework@x.y
version: 2.1
workflows:
  deploy:
    jobs:
      - node/test:
          version: 13.11.0
      - deploy:
          requires:
            - node/test