version: 2.1

workflows:
  build:
    jobs:
       - build
       - deploy:
          requires:
             - build

jobs:
  build:
    docker:
       - image: serverlesspolska/serverless-framework:latest
    steps:
       - checkout
       - run: npm install
       - run: npm install -g mocha
       - run: cd services/user-service
       - run: mocha src/tests/
       - store_test_results:
          path: test-results
  deploy:
    docker:
       - image: serverlesspolska/serverless-framework:latest
    steps:
       - run: sls deploy -v