version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.2.1
  node: circleci/node@3.0.1
  serverless: circleci/serverless-framework@1.0.1

workflows:
  deploy:
    jobs:
      - node/test:
          version: 13.11.0
          app-dir: services/user-service
      - deploy:
          requires:
            - node/test
          context: deckmasterweb-serverless

jobs:
  deploy:
    executor: serverless/default
    steps:
      - checkout
      - run: npm install
      - aws-cli/setup
      - serverless/setup:
          app-name: serverless-framework-orb
          org-name: circleci
      - run:
          command: serverless deploy -v --config services/user-service/serverless.yml
          name: deploy