jobs:
  build-and-test:
    executor:
      "node/default"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - store_test_results:
                path: test-results
  deploy:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup:
          app-name: serverless-framework-orb
          org-name: circleci
      - run:
          command: serverless deploy -v
          name: deploy
orbs:
  aws-cli: circleci/aws-cli@1.2.1
  node: circleci/node@3.0.1
  serverless: circleci/serverless-framework@1.0.1
version: 2.1
workflows:
  build-and-test:
    jobs:
      - build-and-test
  deploy:
    jobs:
      - deploy:
          requires:
            - build-and-test
          context: deckmasterweb-serverless